/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messagefile.proto */

#ifndef PROTOBUF_C_messagefile_2eproto__INCLUDED
#define PROTOBUF_C_messagefile_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _TimeVal TimeVal;
typedef struct _SettimeofdayRequest SettimeofdayRequest;
typedef struct _SettimeofdayResponse SettimeofdayResponse;
typedef struct _GettimeofdayRequest GettimeofdayRequest;
typedef struct _GettimeofdayResponse GettimeofdayResponse;
typedef struct _GettimeofdayResponse__RettimeofdayRequestStatus GettimeofdayResponse__RettimeofdayRequestStatus;
typedef struct _XRPCMessage XRPCMessage;


/* --- enums --- */

typedef enum _XRPCMessage__MessageType {
  X_RPCMESSAGE__MESSAGE_TYPE__REQUEST = 0,
  X_RPCMESSAGE__MESSAGE_TYPE__RESPONSE = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(X_RPCMESSAGE__MESSAGE_TYPE)
} XRPCMessage__MessageType;

/* --- messages --- */

struct  _TimeVal
{
  ProtobufCMessage base;
  /*
   * store time elapse since Jan 1, 1970 00:00 in seconds
   */
  protobuf_c_boolean has_tv_sec;
  uint32_t tv_sec;
  /*
   * store time elapse since Jan 1, 1970 00:00 in microseconds
   */
  protobuf_c_boolean has_tv_usec;
  uint32_t tv_usec;
};
#define TIME_VAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&time_val__descriptor) \
    , 0,0, 0,0 }


struct  _SettimeofdayRequest
{
  ProtobufCMessage base;
  TimeVal *timeval;
};
#define SETTIMEOFDAY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&settimeofday_request__descriptor) \
    , NULL }


struct  _SettimeofdayResponse
{
  ProtobufCMessage base;
  /*
   *stores if function call was succesful or not
   */
  protobuf_c_boolean has_return_value;
  int32_t return_value;
  /*
   *stores error no., if fault occurs
   */
  protobuf_c_boolean has_errno;
  int32_t errno;
};
#define SETTIMEOFDAY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&settimeofday_response__descriptor) \
    , 0,0, 0,0 }


struct  _GettimeofdayRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_stub;
  int32_t stub;
};
#define GETTIMEOFDAY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gettimeofday_request__descriptor) \
    , 0,0 }


/*
 *planning to scrap timezone completely, as it is obsolete
 */
struct  _GettimeofdayResponse__RettimeofdayRequestStatus
{
  ProtobufCMessage base;
  /*
   *stores if function call was succesful or not
   */
  protobuf_c_boolean has_return_value;
  int32_t return_value;
  protobuf_c_boolean has_errno;
  int32_t errno;
};
#define GETTIMEOFDAY_RESPONSE__RETTIMEOFDAY_REQUEST_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gettimeofday_response__rettimeofday_request_status__descriptor) \
    , 0,0, 0,0 }


struct  _GettimeofdayResponse
{
  ProtobufCMessage base;
  TimeVal *timeval;
  GettimeofdayResponse__RettimeofdayRequestStatus *status;
};
#define GETTIMEOFDAY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gettimeofday_response__descriptor) \
    , NULL, NULL }


typedef enum {
  X_RPCMESSAGE__REQUEST_TYPE__NOT_SET = 0,
  X_RPCMESSAGE__REQUEST_TYPE_SETTIMEOFDAY_REQUEST = 3,
  X_RPCMESSAGE__REQUEST_TYPE_GETTIMEOFDAY_REQUEST = 4,
  X_RPCMESSAGE__REQUEST_TYPE_SETTIMEOFDAY_RESPONSE = 1003,
  X_RPCMESSAGE__REQUEST_TYPE_GETTIMEOFDAY_RESPONSE = 1004,
} XRPCMessage__RequestTypeCase;

struct  _XRPCMessage
{
  ProtobufCMessage base;
  protobuf_c_boolean has_message_type;
  XRPCMessage__MessageType message_type;
  TimeVal *time_stamp;
  XRPCMessage__RequestTypeCase request_type_case;
  union {
    SettimeofdayRequest *settimeofday_request;
    GettimeofdayRequest *gettimeofday_request;
    SettimeofdayResponse *settimeofday_response;
    GettimeofdayResponse *gettimeofday_response;
  };
};
#define X_RPCMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&x_rpcmessage__descriptor) \
    , 0,0, NULL, X_RPCMESSAGE__REQUEST_TYPE__NOT_SET, {0} }


/* TimeVal methods */
void   time_val__init
                     (TimeVal         *message);
size_t time_val__get_packed_size
                     (const TimeVal   *message);
size_t time_val__pack
                     (const TimeVal   *message,
                      uint8_t             *out);
size_t time_val__pack_to_buffer
                     (const TimeVal   *message,
                      ProtobufCBuffer     *buffer);
TimeVal *
       time_val__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   time_val__free_unpacked
                     (TimeVal *message,
                      ProtobufCAllocator *allocator);
/* SettimeofdayRequest methods */
void   settimeofday_request__init
                     (SettimeofdayRequest         *message);
size_t settimeofday_request__get_packed_size
                     (const SettimeofdayRequest   *message);
size_t settimeofday_request__pack
                     (const SettimeofdayRequest   *message,
                      uint8_t             *out);
size_t settimeofday_request__pack_to_buffer
                     (const SettimeofdayRequest   *message,
                      ProtobufCBuffer     *buffer);
SettimeofdayRequest *
       settimeofday_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   settimeofday_request__free_unpacked
                     (SettimeofdayRequest *message,
                      ProtobufCAllocator *allocator);
/* SettimeofdayResponse methods */
void   settimeofday_response__init
                     (SettimeofdayResponse         *message);
size_t settimeofday_response__get_packed_size
                     (const SettimeofdayResponse   *message);
size_t settimeofday_response__pack
                     (const SettimeofdayResponse   *message,
                      uint8_t             *out);
size_t settimeofday_response__pack_to_buffer
                     (const SettimeofdayResponse   *message,
                      ProtobufCBuffer     *buffer);
SettimeofdayResponse *
       settimeofday_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   settimeofday_response__free_unpacked
                     (SettimeofdayResponse *message,
                      ProtobufCAllocator *allocator);
/* GettimeofdayRequest methods */
void   gettimeofday_request__init
                     (GettimeofdayRequest         *message);
size_t gettimeofday_request__get_packed_size
                     (const GettimeofdayRequest   *message);
size_t gettimeofday_request__pack
                     (const GettimeofdayRequest   *message,
                      uint8_t             *out);
size_t gettimeofday_request__pack_to_buffer
                     (const GettimeofdayRequest   *message,
                      ProtobufCBuffer     *buffer);
GettimeofdayRequest *
       gettimeofday_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gettimeofday_request__free_unpacked
                     (GettimeofdayRequest *message,
                      ProtobufCAllocator *allocator);
/* GettimeofdayResponse__RettimeofdayRequestStatus methods */
void   gettimeofday_response__rettimeofday_request_status__init
                     (GettimeofdayResponse__RettimeofdayRequestStatus         *message);
/* GettimeofdayResponse methods */
void   gettimeofday_response__init
                     (GettimeofdayResponse         *message);
size_t gettimeofday_response__get_packed_size
                     (const GettimeofdayResponse   *message);
size_t gettimeofday_response__pack
                     (const GettimeofdayResponse   *message,
                      uint8_t             *out);
size_t gettimeofday_response__pack_to_buffer
                     (const GettimeofdayResponse   *message,
                      ProtobufCBuffer     *buffer);
GettimeofdayResponse *
       gettimeofday_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gettimeofday_response__free_unpacked
                     (GettimeofdayResponse *message,
                      ProtobufCAllocator *allocator);
/* XRPCMessage methods */
void   x_rpcmessage__init
                     (XRPCMessage         *message);
size_t x_rpcmessage__get_packed_size
                     (const XRPCMessage   *message);
size_t x_rpcmessage__pack
                     (const XRPCMessage   *message,
                      uint8_t             *out);
size_t x_rpcmessage__pack_to_buffer
                     (const XRPCMessage   *message,
                      ProtobufCBuffer     *buffer);
XRPCMessage *
       x_rpcmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   x_rpcmessage__free_unpacked
                     (XRPCMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TimeVal_Closure)
                 (const TimeVal *message,
                  void *closure_data);
typedef void (*SettimeofdayRequest_Closure)
                 (const SettimeofdayRequest *message,
                  void *closure_data);
typedef void (*SettimeofdayResponse_Closure)
                 (const SettimeofdayResponse *message,
                  void *closure_data);
typedef void (*GettimeofdayRequest_Closure)
                 (const GettimeofdayRequest *message,
                  void *closure_data);
typedef void (*GettimeofdayResponse__RettimeofdayRequestStatus_Closure)
                 (const GettimeofdayResponse__RettimeofdayRequestStatus *message,
                  void *closure_data);
typedef void (*GettimeofdayResponse_Closure)
                 (const GettimeofdayResponse *message,
                  void *closure_data);
typedef void (*XRPCMessage_Closure)
                 (const XRPCMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor time_val__descriptor;
extern const ProtobufCMessageDescriptor settimeofday_request__descriptor;
extern const ProtobufCMessageDescriptor settimeofday_response__descriptor;
extern const ProtobufCMessageDescriptor gettimeofday_request__descriptor;
extern const ProtobufCMessageDescriptor gettimeofday_response__descriptor;
extern const ProtobufCMessageDescriptor gettimeofday_response__rettimeofday_request_status__descriptor;
extern const ProtobufCMessageDescriptor x_rpcmessage__descriptor;
extern const ProtobufCEnumDescriptor    x_rpcmessage__message_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messagefile_2eproto__INCLUDED */
