/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messagefile.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messagefile.pb-c.h"
void   time_val__init
                     (TimeVal         *message)
{
  static TimeVal init_value = TIME_VAL__INIT;
  *message = init_value;
}
size_t time_val__get_packed_size
                     (const TimeVal *message)
{
  assert(message->base.descriptor == &time_val__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_val__pack
                     (const TimeVal *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_val__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_val__pack_to_buffer
                     (const TimeVal *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_val__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimeVal *
       time_val__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimeVal *)
     protobuf_c_message_unpack (&time_val__descriptor,
                                allocator, len, data);
}
void   time_val__free_unpacked
                     (TimeVal *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &time_val__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   settimeofday_request__init
                     (SettimeofdayRequest         *message)
{
  static SettimeofdayRequest init_value = SETTIMEOFDAY_REQUEST__INIT;
  *message = init_value;
}
size_t settimeofday_request__get_packed_size
                     (const SettimeofdayRequest *message)
{
  assert(message->base.descriptor == &settimeofday_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t settimeofday_request__pack
                     (const SettimeofdayRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &settimeofday_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t settimeofday_request__pack_to_buffer
                     (const SettimeofdayRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &settimeofday_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SettimeofdayRequest *
       settimeofday_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SettimeofdayRequest *)
     protobuf_c_message_unpack (&settimeofday_request__descriptor,
                                allocator, len, data);
}
void   settimeofday_request__free_unpacked
                     (SettimeofdayRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &settimeofday_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   settimeofday_response__init
                     (SettimeofdayResponse         *message)
{
  static SettimeofdayResponse init_value = SETTIMEOFDAY_RESPONSE__INIT;
  *message = init_value;
}
size_t settimeofday_response__get_packed_size
                     (const SettimeofdayResponse *message)
{
  assert(message->base.descriptor == &settimeofday_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t settimeofday_response__pack
                     (const SettimeofdayResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &settimeofday_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t settimeofday_response__pack_to_buffer
                     (const SettimeofdayResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &settimeofday_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SettimeofdayResponse *
       settimeofday_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SettimeofdayResponse *)
     protobuf_c_message_unpack (&settimeofday_response__descriptor,
                                allocator, len, data);
}
void   settimeofday_response__free_unpacked
                     (SettimeofdayResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &settimeofday_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gettimeofday_request__init
                     (GettimeofdayRequest         *message)
{
  static GettimeofdayRequest init_value = GETTIMEOFDAY_REQUEST__INIT;
  *message = init_value;
}
size_t gettimeofday_request__get_packed_size
                     (const GettimeofdayRequest *message)
{
  assert(message->base.descriptor == &gettimeofday_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gettimeofday_request__pack
                     (const GettimeofdayRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gettimeofday_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gettimeofday_request__pack_to_buffer
                     (const GettimeofdayRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gettimeofday_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GettimeofdayRequest *
       gettimeofday_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GettimeofdayRequest *)
     protobuf_c_message_unpack (&gettimeofday_request__descriptor,
                                allocator, len, data);
}
void   gettimeofday_request__free_unpacked
                     (GettimeofdayRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &gettimeofday_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gettimeofday_response__rettimeofday_request_status__init
                     (GettimeofdayResponse__RettimeofdayRequestStatus         *message)
{
  static GettimeofdayResponse__RettimeofdayRequestStatus init_value = GETTIMEOFDAY_RESPONSE__RETTIMEOFDAY_REQUEST_STATUS__INIT;
  *message = init_value;
}
void   gettimeofday_response__init
                     (GettimeofdayResponse         *message)
{
  static GettimeofdayResponse init_value = GETTIMEOFDAY_RESPONSE__INIT;
  *message = init_value;
}
size_t gettimeofday_response__get_packed_size
                     (const GettimeofdayResponse *message)
{
  assert(message->base.descriptor == &gettimeofday_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gettimeofday_response__pack
                     (const GettimeofdayResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gettimeofday_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gettimeofday_response__pack_to_buffer
                     (const GettimeofdayResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gettimeofday_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GettimeofdayResponse *
       gettimeofday_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GettimeofdayResponse *)
     protobuf_c_message_unpack (&gettimeofday_response__descriptor,
                                allocator, len, data);
}
void   gettimeofday_response__free_unpacked
                     (GettimeofdayResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &gettimeofday_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   x_rpcmessage__init
                     (XRPCMessage         *message)
{
  static XRPCMessage init_value = X_RPCMESSAGE__INIT;
  *message = init_value;
}
size_t x_rpcmessage__get_packed_size
                     (const XRPCMessage *message)
{
  assert(message->base.descriptor == &x_rpcmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t x_rpcmessage__pack
                     (const XRPCMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &x_rpcmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t x_rpcmessage__pack_to_buffer
                     (const XRPCMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &x_rpcmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
XRPCMessage *
       x_rpcmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (XRPCMessage *)
     protobuf_c_message_unpack (&x_rpcmessage__descriptor,
                                allocator, len, data);
}
void   x_rpcmessage__free_unpacked
                     (XRPCMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &x_rpcmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor time_val__field_descriptors[2] =
{
  {
    "tv_sec",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TimeVal, has_tv_sec),
    offsetof(TimeVal, tv_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tv_usec",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TimeVal, has_tv_usec),
    offsetof(TimeVal, tv_usec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_val__field_indices_by_name[] = {
  0,   /* field[0] = tv_sec */
  1,   /* field[1] = tv_usec */
};
static const ProtobufCIntRange time_val__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor time_val__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimeVal",
  "TimeVal",
  "TimeVal",
  "",
  sizeof(TimeVal),
  2,
  time_val__field_descriptors,
  time_val__field_indices_by_name,
  1,  time_val__number_ranges,
  (ProtobufCMessageInit) time_val__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor settimeofday_request__field_descriptors[1] =
{
  {
    "timeval",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SettimeofdayRequest, timeval),
    &time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned settimeofday_request__field_indices_by_name[] = {
  0,   /* field[0] = timeval */
};
static const ProtobufCIntRange settimeofday_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor settimeofday_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SettimeofdayRequest",
  "SettimeofdayRequest",
  "SettimeofdayRequest",
  "",
  sizeof(SettimeofdayRequest),
  1,
  settimeofday_request__field_descriptors,
  settimeofday_request__field_indices_by_name,
  1,  settimeofday_request__number_ranges,
  (ProtobufCMessageInit) settimeofday_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor settimeofday_response__field_descriptors[2] =
{
  {
    "return_value",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(SettimeofdayResponse, has_return_value),
    offsetof(SettimeofdayResponse, return_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(SettimeofdayResponse, has_errno),
    offsetof(SettimeofdayResponse, errno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned settimeofday_response__field_indices_by_name[] = {
  1,   /* field[1] = errno */
  0,   /* field[0] = return_value */
};
static const ProtobufCIntRange settimeofday_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor settimeofday_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SettimeofdayResponse",
  "SettimeofdayResponse",
  "SettimeofdayResponse",
  "",
  sizeof(SettimeofdayResponse),
  2,
  settimeofday_response__field_descriptors,
  settimeofday_response__field_indices_by_name,
  1,  settimeofday_response__number_ranges,
  (ProtobufCMessageInit) settimeofday_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gettimeofday_request__field_descriptors[1] =
{
  {
    "stub",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(GettimeofdayRequest, has_stub),
    offsetof(GettimeofdayRequest, stub),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gettimeofday_request__field_indices_by_name[] = {
  0,   /* field[0] = stub */
};
static const ProtobufCIntRange gettimeofday_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gettimeofday_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GettimeofdayRequest",
  "GettimeofdayRequest",
  "GettimeofdayRequest",
  "",
  sizeof(GettimeofdayRequest),
  1,
  gettimeofday_request__field_descriptors,
  gettimeofday_request__field_indices_by_name,
  1,  gettimeofday_request__number_ranges,
  (ProtobufCMessageInit) gettimeofday_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gettimeofday_response__rettimeofday_request_status__field_descriptors[2] =
{
  {
    "return_value",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(GettimeofdayResponse__RettimeofdayRequestStatus, has_return_value),
    offsetof(GettimeofdayResponse__RettimeofdayRequestStatus, return_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(GettimeofdayResponse__RettimeofdayRequestStatus, has_errno),
    offsetof(GettimeofdayResponse__RettimeofdayRequestStatus, errno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gettimeofday_response__rettimeofday_request_status__field_indices_by_name[] = {
  1,   /* field[1] = errno */
  0,   /* field[0] = return_value */
};
static const ProtobufCIntRange gettimeofday_response__rettimeofday_request_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gettimeofday_response__rettimeofday_request_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GettimeofdayResponse.RettimeofdayRequestStatus",
  "RettimeofdayRequestStatus",
  "GettimeofdayResponse__RettimeofdayRequestStatus",
  "",
  sizeof(GettimeofdayResponse__RettimeofdayRequestStatus),
  2,
  gettimeofday_response__rettimeofday_request_status__field_descriptors,
  gettimeofday_response__rettimeofday_request_status__field_indices_by_name,
  1,  gettimeofday_response__rettimeofday_request_status__number_ranges,
  (ProtobufCMessageInit) gettimeofday_response__rettimeofday_request_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gettimeofday_response__field_descriptors[2] =
{
  {
    "timeval",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GettimeofdayResponse, timeval),
    &time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GettimeofdayResponse, status),
    &gettimeofday_response__rettimeofday_request_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gettimeofday_response__field_indices_by_name[] = {
  1,   /* field[1] = status */
  0,   /* field[0] = timeval */
};
static const ProtobufCIntRange gettimeofday_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gettimeofday_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GettimeofdayResponse",
  "GettimeofdayResponse",
  "GettimeofdayResponse",
  "",
  sizeof(GettimeofdayResponse),
  2,
  gettimeofday_response__field_descriptors,
  gettimeofday_response__field_indices_by_name,
  1,  gettimeofday_response__number_ranges,
  (ProtobufCMessageInit) gettimeofday_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue x_rpcmessage__message_type__enum_values_by_number[2] =
{
  { "REQUEST", "X_RPCMESSAGE__MESSAGE_TYPE__REQUEST", 0 },
  { "RESPONSE", "X_RPCMESSAGE__MESSAGE_TYPE__RESPONSE", 1 },
};
static const ProtobufCIntRange x_rpcmessage__message_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex x_rpcmessage__message_type__enum_values_by_name[2] =
{
  { "REQUEST", 0 },
  { "RESPONSE", 1 },
};
const ProtobufCEnumDescriptor x_rpcmessage__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "xRPCMessage.MessageType",
  "MessageType",
  "XRPCMessage__MessageType",
  "",
  2,
  x_rpcmessage__message_type__enum_values_by_number,
  2,
  x_rpcmessage__message_type__enum_values_by_name,
  1,
  x_rpcmessage__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor x_rpcmessage__field_descriptors[6] =
{
  {
    "message_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(XRPCMessage, has_message_type),
    offsetof(XRPCMessage, message_type),
    &x_rpcmessage__message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_stamp",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(XRPCMessage, time_stamp),
    &time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "settimeofday_request",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XRPCMessage, request_type_case),
    offsetof(XRPCMessage, settimeofday_request),
    &settimeofday_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gettimeofday_request",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XRPCMessage, request_type_case),
    offsetof(XRPCMessage, gettimeofday_request),
    &gettimeofday_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "settimeofday_response",
    1003,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XRPCMessage, request_type_case),
    offsetof(XRPCMessage, settimeofday_response),
    &settimeofday_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gettimeofday_response",
    1004,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XRPCMessage, request_type_case),
    offsetof(XRPCMessage, gettimeofday_response),
    &gettimeofday_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned x_rpcmessage__field_indices_by_name[] = {
  3,   /* field[3] = gettimeofday_request */
  5,   /* field[5] = gettimeofday_response */
  0,   /* field[0] = message_type */
  2,   /* field[2] = settimeofday_request */
  4,   /* field[4] = settimeofday_response */
  1,   /* field[1] = time_stamp */
};
static const ProtobufCIntRange x_rpcmessage__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 1003, 4 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor x_rpcmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xRPCMessage",
  "XRPCMessage",
  "XRPCMessage",
  "",
  sizeof(XRPCMessage),
  6,
  x_rpcmessage__field_descriptors,
  x_rpcmessage__field_indices_by_name,
  2,  x_rpcmessage__number_ranges,
  (ProtobufCMessageInit) x_rpcmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
