/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messagefile.proto */

#ifndef PROTOBUF_C_messagefile_2eproto__INCLUDED
#define PROTOBUF_C_messagefile_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _TimeVal TimeVal;
typedef struct _LedcChannelConfigT LedcChannelConfigT;
typedef struct _LedcIntrTypeT LedcIntrTypeT;
typedef struct _LedcChannelT LedcChannelT;
typedef struct _LedcModeT LedcModeT;
typedef struct _I2cOperationsRequest I2cOperationsRequest;
typedef struct _I2cOperationsResponse I2cOperationsResponse;
typedef struct _SettimeofdayRequest SettimeofdayRequest;
typedef struct _SettimeofdayResponse SettimeofdayResponse;
typedef struct _GettimeofdayRequest GettimeofdayRequest;
typedef struct _GettimeofdayResponse GettimeofdayResponse;
typedef struct _LedcChannelConfigRequest LedcChannelConfigRequest;
typedef struct _LedcChannelConfigResponse LedcChannelConfigResponse;
typedef struct _Request Request;
typedef struct _Response Response;
typedef struct _XRPCMessage XRPCMessage;


/* --- enums --- */

typedef enum _LedcIntrTypeT__InterruptType {
  LEDC_INTR_TYPE_T__INTERRUPT_TYPE__LEDC_INTR_DISABLE = 0,
  LEDC_INTR_TYPE_T__INTERRUPT_TYPE__LEDC_INTR_FADE_END = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LEDC_INTR_TYPE_T__INTERRUPT_TYPE)
} LedcIntrTypeT__InterruptType;
typedef enum _LedcModeT__LedcModeE {
  LEDC_MODE_T__LEDC_MODE_E__LEDC_HIGH_SPEED_MODE = 0,
  LEDC_MODE_T__LEDC_MODE_E__LEDC_LOW_SPEED_MODE = 1,
  LEDC_MODE_T__LEDC_MODE_E__LEDC_SPEED_MODE_MAX = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LEDC_MODE_T__LEDC_MODE_E)
} LedcModeT__LedcModeE;

/* --- messages --- */

struct  _TimeVal
{
  ProtobufCMessage base;
  /*
   * store time elapse since Jan 1, 1970 00:00 in seconds
   */
  uint32_t tv_sec;
  /*
   * store time elapse since Jan 1, 1970 00:00 in microseconds
   */
  uint32_t tv_usec;
};
#define TIME_VAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&time_val__descriptor) \
    , 0, 0 }


struct  _LedcChannelConfigT
{
  ProtobufCMessage base;
  int32_t gpio_num;
  LedcModeT *speed_mode;
  LedcChannelT *channel;
  LedcIntrTypeT *intr_type;
  uint32_t duty;
  int32_t hpoint;
};
#define LEDC_CHANNEL_CONFIG_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ledc_channel_config_t__descriptor) \
    , 0, NULL, NULL, NULL, 0, 0 }


struct  _LedcIntrTypeT
{
  ProtobufCMessage base;
  LedcIntrTypeT__InterruptType intr;
};
#define LEDC_INTR_TYPE_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ledc_intr_type_t__descriptor) \
    , LEDC_INTR_TYPE_T__INTERRUPT_TYPE__LEDC_INTR_DISABLE }


struct  _LedcChannelT
{
  ProtobufCMessage base;
  int32_t channel;
};
#define LEDC_CHANNEL_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ledc_channel_t__descriptor) \
    , 0 }


struct  _LedcModeT
{
  ProtobufCMessage base;
  LedcModeT__LedcModeE ledc_speed;
};
#define LEDC_MODE_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ledc_mode_t__descriptor) \
    , LEDC_MODE_T__LEDC_MODE_E__LEDC_HIGH_SPEED_MODE }


struct  _I2cOperationsRequest
{
  ProtobufCMessage base;
  int32_t master_sda_gpio;
  int32_t master_scl_gpio;
  int32_t clock_speed;
  int32_t slave_addr;
  int32_t slave_sda_gpio;
  int32_t slave_scl_gpio;
};
#define I2C_OPERATIONS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i2c_operations_request__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


struct  _I2cOperationsResponse
{
  ProtobufCMessage base;
  int32_t success;
};
#define I2C_OPERATIONS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i2c_operations_response__descriptor) \
    , 0 }


struct  _SettimeofdayRequest
{
  ProtobufCMessage base;
  TimeVal *timeval;
};
#define SETTIMEOFDAY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&settimeofday_request__descriptor) \
    , NULL }


struct  _SettimeofdayResponse
{
  ProtobufCMessage base;
  /*
   *stores if function call was succesful or not
   */
  int32_t return_value;
  /*
   *stores error no., if fault occurs
   */
  int32_t errno_alt;
};
#define SETTIMEOFDAY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&settimeofday_response__descriptor) \
    , 0, 0 }


struct  _GettimeofdayRequest
{
  ProtobufCMessage base;
  int32_t stub;
};
#define GETTIMEOFDAY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gettimeofday_request__descriptor) \
    , 0 }


struct  _GettimeofdayResponse
{
  ProtobufCMessage base;
  /*
   *planning to scrap timezone completely, as it is obsolete
   */
  /*
   *stores if function call was succesful or not
   */
  int32_t return_value;
  int32_t errno_alt;
  TimeVal *timeval;
};
#define GETTIMEOFDAY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gettimeofday_response__descriptor) \
    , 0, 0, NULL }


struct  _LedcChannelConfigRequest
{
  ProtobufCMessage base;
  LedcChannelConfigT *ledc_conf;
};
#define LEDC_CHANNEL_CONFIG__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ledc_channel_config__request__descriptor) \
    , NULL }


struct  _LedcChannelConfigResponse
{
  ProtobufCMessage base;
  int32_t config_status;
};
#define LEDC_CHANNEL_CONFIG__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ledc_channel_config__response__descriptor) \
    , 0 }


typedef enum {
  REQUEST__REQUEST_FUNC__NOT_SET = 0,
  REQUEST__REQUEST_FUNC_SETTIMEOFDAY_REQUEST = 1,
  REQUEST__REQUEST_FUNC_GETTIMEOFDAY_REQUEST = 2,
  REQUEST__REQUEST_FUNC_LEDC_CHANNEL_CONFIG_REQUEST = 3,
  REQUEST__REQUEST_FUNC_I2C_REQUEST = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(REQUEST__REQUEST_FUNC)
} Request__RequestFuncCase;

struct  _Request
{
  ProtobufCMessage base;
  Request__RequestFuncCase request_func_case;
  union {
    SettimeofdayRequest *settimeofday_request;
    GettimeofdayRequest *gettimeofday_request;
    LedcChannelConfigRequest *ledc_channel_config_request;
    I2cOperationsRequest *i2c_request;
  };
};
#define REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&request__descriptor) \
    , REQUEST__REQUEST_FUNC__NOT_SET, {0} }


typedef enum {
  RESPONSE__RESPONSE_FUNC__NOT_SET = 0,
  RESPONSE__RESPONSE_FUNC_SETTIMEOFDAY_RESPONSE = 1,
  RESPONSE__RESPONSE_FUNC_GETTIMEOFDAY_RESPONSE = 2,
  RESPONSE__RESPONSE_FUNC_LEDC_CHANNEL_CONFIG_RESPONSE = 3,
  RESPONSE__RESPONSE_FUNC_I2C_RESPONSE = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RESPONSE__RESPONSE_FUNC)
} Response__ResponseFuncCase;

struct  _Response
{
  ProtobufCMessage base;
  Response__ResponseFuncCase response_func_case;
  union {
    SettimeofdayResponse *settimeofday_response;
    GettimeofdayResponse *gettimeofday_response;
    LedcChannelConfigResponse *ledc_channel_config_response;
    I2cOperationsResponse *i2c_response;
  };
};
#define RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&response__descriptor) \
    , RESPONSE__RESPONSE_FUNC__NOT_SET, {0} }


typedef enum {
  X_RPCMESSAGE__MESSAGE_TYPE__NOT_SET = 0,
  X_RPCMESSAGE__MESSAGE_TYPE_REQUEST = 1,
  X_RPCMESSAGE__MESSAGE_TYPE_RESPONSE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(X_RPCMESSAGE__MESSAGE_TYPE)
} XRPCMessage__MessageTypeCase;

struct  _XRPCMessage
{
  ProtobufCMessage base;
  TimeVal *time_stamp;
  XRPCMessage__MessageTypeCase message_type_case;
  union {
    Request *request;
    Response *response;
  };
};
#define X_RPCMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&x_rpcmessage__descriptor) \
    , NULL, X_RPCMESSAGE__MESSAGE_TYPE__NOT_SET, {0} }


/* TimeVal methods */
void   time_val__init
                     (TimeVal         *message);
size_t time_val__get_packed_size
                     (const TimeVal   *message);
size_t time_val__pack
                     (const TimeVal   *message,
                      uint8_t             *out);
size_t time_val__pack_to_buffer
                     (const TimeVal   *message,
                      ProtobufCBuffer     *buffer);
TimeVal *
       time_val__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   time_val__free_unpacked
                     (TimeVal *message,
                      ProtobufCAllocator *allocator);
/* LedcChannelConfigT methods */
void   ledc_channel_config_t__init
                     (LedcChannelConfigT         *message);
size_t ledc_channel_config_t__get_packed_size
                     (const LedcChannelConfigT   *message);
size_t ledc_channel_config_t__pack
                     (const LedcChannelConfigT   *message,
                      uint8_t             *out);
size_t ledc_channel_config_t__pack_to_buffer
                     (const LedcChannelConfigT   *message,
                      ProtobufCBuffer     *buffer);
LedcChannelConfigT *
       ledc_channel_config_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ledc_channel_config_t__free_unpacked
                     (LedcChannelConfigT *message,
                      ProtobufCAllocator *allocator);
/* LedcIntrTypeT methods */
void   ledc_intr_type_t__init
                     (LedcIntrTypeT         *message);
size_t ledc_intr_type_t__get_packed_size
                     (const LedcIntrTypeT   *message);
size_t ledc_intr_type_t__pack
                     (const LedcIntrTypeT   *message,
                      uint8_t             *out);
size_t ledc_intr_type_t__pack_to_buffer
                     (const LedcIntrTypeT   *message,
                      ProtobufCBuffer     *buffer);
LedcIntrTypeT *
       ledc_intr_type_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ledc_intr_type_t__free_unpacked
                     (LedcIntrTypeT *message,
                      ProtobufCAllocator *allocator);
/* LedcChannelT methods */
void   ledc_channel_t__init
                     (LedcChannelT         *message);
size_t ledc_channel_t__get_packed_size
                     (const LedcChannelT   *message);
size_t ledc_channel_t__pack
                     (const LedcChannelT   *message,
                      uint8_t             *out);
size_t ledc_channel_t__pack_to_buffer
                     (const LedcChannelT   *message,
                      ProtobufCBuffer     *buffer);
LedcChannelT *
       ledc_channel_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ledc_channel_t__free_unpacked
                     (LedcChannelT *message,
                      ProtobufCAllocator *allocator);
/* LedcModeT methods */
void   ledc_mode_t__init
                     (LedcModeT         *message);
size_t ledc_mode_t__get_packed_size
                     (const LedcModeT   *message);
size_t ledc_mode_t__pack
                     (const LedcModeT   *message,
                      uint8_t             *out);
size_t ledc_mode_t__pack_to_buffer
                     (const LedcModeT   *message,
                      ProtobufCBuffer     *buffer);
LedcModeT *
       ledc_mode_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ledc_mode_t__free_unpacked
                     (LedcModeT *message,
                      ProtobufCAllocator *allocator);
/* I2cOperationsRequest methods */
void   i2c_operations_request__init
                     (I2cOperationsRequest         *message);
size_t i2c_operations_request__get_packed_size
                     (const I2cOperationsRequest   *message);
size_t i2c_operations_request__pack
                     (const I2cOperationsRequest   *message,
                      uint8_t             *out);
size_t i2c_operations_request__pack_to_buffer
                     (const I2cOperationsRequest   *message,
                      ProtobufCBuffer     *buffer);
I2cOperationsRequest *
       i2c_operations_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i2c_operations_request__free_unpacked
                     (I2cOperationsRequest *message,
                      ProtobufCAllocator *allocator);
/* I2cOperationsResponse methods */
void   i2c_operations_response__init
                     (I2cOperationsResponse         *message);
size_t i2c_operations_response__get_packed_size
                     (const I2cOperationsResponse   *message);
size_t i2c_operations_response__pack
                     (const I2cOperationsResponse   *message,
                      uint8_t             *out);
size_t i2c_operations_response__pack_to_buffer
                     (const I2cOperationsResponse   *message,
                      ProtobufCBuffer     *buffer);
I2cOperationsResponse *
       i2c_operations_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i2c_operations_response__free_unpacked
                     (I2cOperationsResponse *message,
                      ProtobufCAllocator *allocator);
/* SettimeofdayRequest methods */
void   settimeofday_request__init
                     (SettimeofdayRequest         *message);
size_t settimeofday_request__get_packed_size
                     (const SettimeofdayRequest   *message);
size_t settimeofday_request__pack
                     (const SettimeofdayRequest   *message,
                      uint8_t             *out);
size_t settimeofday_request__pack_to_buffer
                     (const SettimeofdayRequest   *message,
                      ProtobufCBuffer     *buffer);
SettimeofdayRequest *
       settimeofday_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   settimeofday_request__free_unpacked
                     (SettimeofdayRequest *message,
                      ProtobufCAllocator *allocator);
/* SettimeofdayResponse methods */
void   settimeofday_response__init
                     (SettimeofdayResponse         *message);
size_t settimeofday_response__get_packed_size
                     (const SettimeofdayResponse   *message);
size_t settimeofday_response__pack
                     (const SettimeofdayResponse   *message,
                      uint8_t             *out);
size_t settimeofday_response__pack_to_buffer
                     (const SettimeofdayResponse   *message,
                      ProtobufCBuffer     *buffer);
SettimeofdayResponse *
       settimeofday_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   settimeofday_response__free_unpacked
                     (SettimeofdayResponse *message,
                      ProtobufCAllocator *allocator);
/* GettimeofdayRequest methods */
void   gettimeofday_request__init
                     (GettimeofdayRequest         *message);
size_t gettimeofday_request__get_packed_size
                     (const GettimeofdayRequest   *message);
size_t gettimeofday_request__pack
                     (const GettimeofdayRequest   *message,
                      uint8_t             *out);
size_t gettimeofday_request__pack_to_buffer
                     (const GettimeofdayRequest   *message,
                      ProtobufCBuffer     *buffer);
GettimeofdayRequest *
       gettimeofday_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gettimeofday_request__free_unpacked
                     (GettimeofdayRequest *message,
                      ProtobufCAllocator *allocator);
/* GettimeofdayResponse methods */
void   gettimeofday_response__init
                     (GettimeofdayResponse         *message);
size_t gettimeofday_response__get_packed_size
                     (const GettimeofdayResponse   *message);
size_t gettimeofday_response__pack
                     (const GettimeofdayResponse   *message,
                      uint8_t             *out);
size_t gettimeofday_response__pack_to_buffer
                     (const GettimeofdayResponse   *message,
                      ProtobufCBuffer     *buffer);
GettimeofdayResponse *
       gettimeofday_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gettimeofday_response__free_unpacked
                     (GettimeofdayResponse *message,
                      ProtobufCAllocator *allocator);
/* LedcChannelConfigRequest methods */
void   ledc_channel_config__request__init
                     (LedcChannelConfigRequest         *message);
size_t ledc_channel_config__request__get_packed_size
                     (const LedcChannelConfigRequest   *message);
size_t ledc_channel_config__request__pack
                     (const LedcChannelConfigRequest   *message,
                      uint8_t             *out);
size_t ledc_channel_config__request__pack_to_buffer
                     (const LedcChannelConfigRequest   *message,
                      ProtobufCBuffer     *buffer);
LedcChannelConfigRequest *
       ledc_channel_config__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ledc_channel_config__request__free_unpacked
                     (LedcChannelConfigRequest *message,
                      ProtobufCAllocator *allocator);
/* LedcChannelConfigResponse methods */
void   ledc_channel_config__response__init
                     (LedcChannelConfigResponse         *message);
size_t ledc_channel_config__response__get_packed_size
                     (const LedcChannelConfigResponse   *message);
size_t ledc_channel_config__response__pack
                     (const LedcChannelConfigResponse   *message,
                      uint8_t             *out);
size_t ledc_channel_config__response__pack_to_buffer
                     (const LedcChannelConfigResponse   *message,
                      ProtobufCBuffer     *buffer);
LedcChannelConfigResponse *
       ledc_channel_config__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ledc_channel_config__response__free_unpacked
                     (LedcChannelConfigResponse *message,
                      ProtobufCAllocator *allocator);
/* Request methods */
void   request__init
                     (Request         *message);
size_t request__get_packed_size
                     (const Request   *message);
size_t request__pack
                     (const Request   *message,
                      uint8_t             *out);
size_t request__pack_to_buffer
                     (const Request   *message,
                      ProtobufCBuffer     *buffer);
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator);
/* Response methods */
void   response__init
                     (Response         *message);
size_t response__get_packed_size
                     (const Response   *message);
size_t response__pack
                     (const Response   *message,
                      uint8_t             *out);
size_t response__pack_to_buffer
                     (const Response   *message,
                      ProtobufCBuffer     *buffer);
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator);
/* XRPCMessage methods */
void   x_rpcmessage__init
                     (XRPCMessage         *message);
size_t x_rpcmessage__get_packed_size
                     (const XRPCMessage   *message);
size_t x_rpcmessage__pack
                     (const XRPCMessage   *message,
                      uint8_t             *out);
size_t x_rpcmessage__pack_to_buffer
                     (const XRPCMessage   *message,
                      ProtobufCBuffer     *buffer);
XRPCMessage *
       x_rpcmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   x_rpcmessage__free_unpacked
                     (XRPCMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TimeVal_Closure)
                 (const TimeVal *message,
                  void *closure_data);
typedef void (*LedcChannelConfigT_Closure)
                 (const LedcChannelConfigT *message,
                  void *closure_data);
typedef void (*LedcIntrTypeT_Closure)
                 (const LedcIntrTypeT *message,
                  void *closure_data);
typedef void (*LedcChannelT_Closure)
                 (const LedcChannelT *message,
                  void *closure_data);
typedef void (*LedcModeT_Closure)
                 (const LedcModeT *message,
                  void *closure_data);
typedef void (*I2cOperationsRequest_Closure)
                 (const I2cOperationsRequest *message,
                  void *closure_data);
typedef void (*I2cOperationsResponse_Closure)
                 (const I2cOperationsResponse *message,
                  void *closure_data);
typedef void (*SettimeofdayRequest_Closure)
                 (const SettimeofdayRequest *message,
                  void *closure_data);
typedef void (*SettimeofdayResponse_Closure)
                 (const SettimeofdayResponse *message,
                  void *closure_data);
typedef void (*GettimeofdayRequest_Closure)
                 (const GettimeofdayRequest *message,
                  void *closure_data);
typedef void (*GettimeofdayResponse_Closure)
                 (const GettimeofdayResponse *message,
                  void *closure_data);
typedef void (*LedcChannelConfigRequest_Closure)
                 (const LedcChannelConfigRequest *message,
                  void *closure_data);
typedef void (*LedcChannelConfigResponse_Closure)
                 (const LedcChannelConfigResponse *message,
                  void *closure_data);
typedef void (*Request_Closure)
                 (const Request *message,
                  void *closure_data);
typedef void (*Response_Closure)
                 (const Response *message,
                  void *closure_data);
typedef void (*XRPCMessage_Closure)
                 (const XRPCMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor time_val__descriptor;
extern const ProtobufCMessageDescriptor ledc_channel_config_t__descriptor;
extern const ProtobufCMessageDescriptor ledc_intr_type_t__descriptor;
extern const ProtobufCEnumDescriptor    ledc_intr_type_t__interrupt_type__descriptor;
extern const ProtobufCMessageDescriptor ledc_channel_t__descriptor;
extern const ProtobufCMessageDescriptor ledc_mode_t__descriptor;
extern const ProtobufCEnumDescriptor    ledc_mode_t__ledc_mode_e__descriptor;
extern const ProtobufCMessageDescriptor i2c_operations_request__descriptor;
extern const ProtobufCMessageDescriptor i2c_operations_response__descriptor;
extern const ProtobufCMessageDescriptor settimeofday_request__descriptor;
extern const ProtobufCMessageDescriptor settimeofday_response__descriptor;
extern const ProtobufCMessageDescriptor gettimeofday_request__descriptor;
extern const ProtobufCMessageDescriptor gettimeofday_response__descriptor;
extern const ProtobufCMessageDescriptor ledc_channel_config__request__descriptor;
extern const ProtobufCMessageDescriptor ledc_channel_config__response__descriptor;
extern const ProtobufCMessageDescriptor request__descriptor;
extern const ProtobufCMessageDescriptor response__descriptor;
extern const ProtobufCMessageDescriptor x_rpcmessage__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messagefile_2eproto__INCLUDED */
