/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messagefile.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messagefile.pb-c.h"
void   time_val__init
                     (TimeVal         *message)
{
  static const TimeVal init_value = TIME_VAL__INIT;
  *message = init_value;
}
size_t time_val__get_packed_size
                     (const TimeVal *message)
{
  assert(message->base.descriptor == &time_val__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_val__pack
                     (const TimeVal *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_val__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_val__pack_to_buffer
                     (const TimeVal *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_val__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimeVal *
       time_val__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimeVal *)
     protobuf_c_message_unpack (&time_val__descriptor,
                                allocator, len, data);
}
void   time_val__free_unpacked
                     (TimeVal *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &time_val__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ledc_channel_config_t__init
                     (LedcChannelConfigT         *message)
{
  static const LedcChannelConfigT init_value = LEDC_CHANNEL_CONFIG_T__INIT;
  *message = init_value;
}
size_t ledc_channel_config_t__get_packed_size
                     (const LedcChannelConfigT *message)
{
  assert(message->base.descriptor == &ledc_channel_config_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ledc_channel_config_t__pack
                     (const LedcChannelConfigT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ledc_channel_config_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ledc_channel_config_t__pack_to_buffer
                     (const LedcChannelConfigT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ledc_channel_config_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LedcChannelConfigT *
       ledc_channel_config_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LedcChannelConfigT *)
     protobuf_c_message_unpack (&ledc_channel_config_t__descriptor,
                                allocator, len, data);
}
void   ledc_channel_config_t__free_unpacked
                     (LedcChannelConfigT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ledc_channel_config_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ledc_intr_type_t__init
                     (LedcIntrTypeT         *message)
{
  static const LedcIntrTypeT init_value = LEDC_INTR_TYPE_T__INIT;
  *message = init_value;
}
size_t ledc_intr_type_t__get_packed_size
                     (const LedcIntrTypeT *message)
{
  assert(message->base.descriptor == &ledc_intr_type_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ledc_intr_type_t__pack
                     (const LedcIntrTypeT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ledc_intr_type_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ledc_intr_type_t__pack_to_buffer
                     (const LedcIntrTypeT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ledc_intr_type_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LedcIntrTypeT *
       ledc_intr_type_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LedcIntrTypeT *)
     protobuf_c_message_unpack (&ledc_intr_type_t__descriptor,
                                allocator, len, data);
}
void   ledc_intr_type_t__free_unpacked
                     (LedcIntrTypeT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ledc_intr_type_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ledc_channel_t__init
                     (LedcChannelT         *message)
{
  static const LedcChannelT init_value = LEDC_CHANNEL_T__INIT;
  *message = init_value;
}
size_t ledc_channel_t__get_packed_size
                     (const LedcChannelT *message)
{
  assert(message->base.descriptor == &ledc_channel_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ledc_channel_t__pack
                     (const LedcChannelT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ledc_channel_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ledc_channel_t__pack_to_buffer
                     (const LedcChannelT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ledc_channel_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LedcChannelT *
       ledc_channel_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LedcChannelT *)
     protobuf_c_message_unpack (&ledc_channel_t__descriptor,
                                allocator, len, data);
}
void   ledc_channel_t__free_unpacked
                     (LedcChannelT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ledc_channel_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ledc_mode_t__init
                     (LedcModeT         *message)
{
  static const LedcModeT init_value = LEDC_MODE_T__INIT;
  *message = init_value;
}
size_t ledc_mode_t__get_packed_size
                     (const LedcModeT *message)
{
  assert(message->base.descriptor == &ledc_mode_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ledc_mode_t__pack
                     (const LedcModeT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ledc_mode_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ledc_mode_t__pack_to_buffer
                     (const LedcModeT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ledc_mode_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LedcModeT *
       ledc_mode_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LedcModeT *)
     protobuf_c_message_unpack (&ledc_mode_t__descriptor,
                                allocator, len, data);
}
void   ledc_mode_t__free_unpacked
                     (LedcModeT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ledc_mode_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i2c_operations_request__init
                     (I2cOperationsRequest         *message)
{
  static const I2cOperationsRequest init_value = I2C_OPERATIONS_REQUEST__INIT;
  *message = init_value;
}
size_t i2c_operations_request__get_packed_size
                     (const I2cOperationsRequest *message)
{
  assert(message->base.descriptor == &i2c_operations_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i2c_operations_request__pack
                     (const I2cOperationsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &i2c_operations_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i2c_operations_request__pack_to_buffer
                     (const I2cOperationsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &i2c_operations_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
I2cOperationsRequest *
       i2c_operations_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (I2cOperationsRequest *)
     protobuf_c_message_unpack (&i2c_operations_request__descriptor,
                                allocator, len, data);
}
void   i2c_operations_request__free_unpacked
                     (I2cOperationsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &i2c_operations_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i2c_operations_response__init
                     (I2cOperationsResponse         *message)
{
  static const I2cOperationsResponse init_value = I2C_OPERATIONS_RESPONSE__INIT;
  *message = init_value;
}
size_t i2c_operations_response__get_packed_size
                     (const I2cOperationsResponse *message)
{
  assert(message->base.descriptor == &i2c_operations_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i2c_operations_response__pack
                     (const I2cOperationsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &i2c_operations_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i2c_operations_response__pack_to_buffer
                     (const I2cOperationsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &i2c_operations_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
I2cOperationsResponse *
       i2c_operations_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (I2cOperationsResponse *)
     protobuf_c_message_unpack (&i2c_operations_response__descriptor,
                                allocator, len, data);
}
void   i2c_operations_response__free_unpacked
                     (I2cOperationsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &i2c_operations_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   settimeofday_request__init
                     (SettimeofdayRequest         *message)
{
  static const SettimeofdayRequest init_value = SETTIMEOFDAY_REQUEST__INIT;
  *message = init_value;
}
size_t settimeofday_request__get_packed_size
                     (const SettimeofdayRequest *message)
{
  assert(message->base.descriptor == &settimeofday_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t settimeofday_request__pack
                     (const SettimeofdayRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &settimeofday_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t settimeofday_request__pack_to_buffer
                     (const SettimeofdayRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &settimeofday_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SettimeofdayRequest *
       settimeofday_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SettimeofdayRequest *)
     protobuf_c_message_unpack (&settimeofday_request__descriptor,
                                allocator, len, data);
}
void   settimeofday_request__free_unpacked
                     (SettimeofdayRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &settimeofday_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   settimeofday_response__init
                     (SettimeofdayResponse         *message)
{
  static const SettimeofdayResponse init_value = SETTIMEOFDAY_RESPONSE__INIT;
  *message = init_value;
}
size_t settimeofday_response__get_packed_size
                     (const SettimeofdayResponse *message)
{
  assert(message->base.descriptor == &settimeofday_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t settimeofday_response__pack
                     (const SettimeofdayResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &settimeofday_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t settimeofday_response__pack_to_buffer
                     (const SettimeofdayResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &settimeofday_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SettimeofdayResponse *
       settimeofday_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SettimeofdayResponse *)
     protobuf_c_message_unpack (&settimeofday_response__descriptor,
                                allocator, len, data);
}
void   settimeofday_response__free_unpacked
                     (SettimeofdayResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &settimeofday_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gettimeofday_request__init
                     (GettimeofdayRequest         *message)
{
  static const GettimeofdayRequest init_value = GETTIMEOFDAY_REQUEST__INIT;
  *message = init_value;
}
size_t gettimeofday_request__get_packed_size
                     (const GettimeofdayRequest *message)
{
  assert(message->base.descriptor == &gettimeofday_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gettimeofday_request__pack
                     (const GettimeofdayRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gettimeofday_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gettimeofday_request__pack_to_buffer
                     (const GettimeofdayRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gettimeofday_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GettimeofdayRequest *
       gettimeofday_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GettimeofdayRequest *)
     protobuf_c_message_unpack (&gettimeofday_request__descriptor,
                                allocator, len, data);
}
void   gettimeofday_request__free_unpacked
                     (GettimeofdayRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gettimeofday_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gettimeofday_response__init
                     (GettimeofdayResponse         *message)
{
  static const GettimeofdayResponse init_value = GETTIMEOFDAY_RESPONSE__INIT;
  *message = init_value;
}
size_t gettimeofday_response__get_packed_size
                     (const GettimeofdayResponse *message)
{
  assert(message->base.descriptor == &gettimeofday_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gettimeofday_response__pack
                     (const GettimeofdayResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gettimeofday_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gettimeofday_response__pack_to_buffer
                     (const GettimeofdayResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gettimeofday_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GettimeofdayResponse *
       gettimeofday_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GettimeofdayResponse *)
     protobuf_c_message_unpack (&gettimeofday_response__descriptor,
                                allocator, len, data);
}
void   gettimeofday_response__free_unpacked
                     (GettimeofdayResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gettimeofday_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ledc_channel_config__request__init
                     (LedcChannelConfigRequest         *message)
{
  static const LedcChannelConfigRequest init_value = LEDC_CHANNEL_CONFIG__REQUEST__INIT;
  *message = init_value;
}
size_t ledc_channel_config__request__get_packed_size
                     (const LedcChannelConfigRequest *message)
{
  assert(message->base.descriptor == &ledc_channel_config__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ledc_channel_config__request__pack
                     (const LedcChannelConfigRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ledc_channel_config__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ledc_channel_config__request__pack_to_buffer
                     (const LedcChannelConfigRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ledc_channel_config__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LedcChannelConfigRequest *
       ledc_channel_config__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LedcChannelConfigRequest *)
     protobuf_c_message_unpack (&ledc_channel_config__request__descriptor,
                                allocator, len, data);
}
void   ledc_channel_config__request__free_unpacked
                     (LedcChannelConfigRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ledc_channel_config__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ledc_channel_config__response__init
                     (LedcChannelConfigResponse         *message)
{
  static const LedcChannelConfigResponse init_value = LEDC_CHANNEL_CONFIG__RESPONSE__INIT;
  *message = init_value;
}
size_t ledc_channel_config__response__get_packed_size
                     (const LedcChannelConfigResponse *message)
{
  assert(message->base.descriptor == &ledc_channel_config__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ledc_channel_config__response__pack
                     (const LedcChannelConfigResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ledc_channel_config__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ledc_channel_config__response__pack_to_buffer
                     (const LedcChannelConfigResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ledc_channel_config__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LedcChannelConfigResponse *
       ledc_channel_config__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LedcChannelConfigResponse *)
     protobuf_c_message_unpack (&ledc_channel_config__response__descriptor,
                                allocator, len, data);
}
void   ledc_channel_config__response__free_unpacked
                     (LedcChannelConfigResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ledc_channel_config__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request__init
                     (Request         *message)
{
  static const Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   x_rpcmessage__init
                     (XRPCMessage         *message)
{
  static const XRPCMessage init_value = X_RPCMESSAGE__INIT;
  *message = init_value;
}
size_t x_rpcmessage__get_packed_size
                     (const XRPCMessage *message)
{
  assert(message->base.descriptor == &x_rpcmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t x_rpcmessage__pack
                     (const XRPCMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &x_rpcmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t x_rpcmessage__pack_to_buffer
                     (const XRPCMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &x_rpcmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
XRPCMessage *
       x_rpcmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (XRPCMessage *)
     protobuf_c_message_unpack (&x_rpcmessage__descriptor,
                                allocator, len, data);
}
void   x_rpcmessage__free_unpacked
                     (XRPCMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &x_rpcmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor time_val__field_descriptors[2] =
{
  {
    "tv_sec",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimeVal, tv_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tv_usec",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimeVal, tv_usec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_val__field_indices_by_name[] = {
  0,   /* field[0] = tv_sec */
  1,   /* field[1] = tv_usec */
};
static const ProtobufCIntRange time_val__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor time_val__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimeVal",
  "TimeVal",
  "TimeVal",
  "",
  sizeof(TimeVal),
  2,
  time_val__field_descriptors,
  time_val__field_indices_by_name,
  1,  time_val__number_ranges,
  (ProtobufCMessageInit) time_val__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ledc_channel_config_t__field_descriptors[6] =
{
  {
    "gpio_num",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LedcChannelConfigT, gpio_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed_mode",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LedcChannelConfigT, speed_mode),
    &ledc_mode_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LedcChannelConfigT, channel),
    &ledc_channel_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "intr_type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LedcChannelConfigT, intr_type),
    &ledc_intr_type_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duty",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LedcChannelConfigT, duty),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hpoint",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LedcChannelConfigT, hpoint),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ledc_channel_config_t__field_indices_by_name[] = {
  2,   /* field[2] = channel */
  4,   /* field[4] = duty */
  0,   /* field[0] = gpio_num */
  5,   /* field[5] = hpoint */
  3,   /* field[3] = intr_type */
  1,   /* field[1] = speed_mode */
};
static const ProtobufCIntRange ledc_channel_config_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor ledc_channel_config_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ledc_channel_config_t",
  "LedcChannelConfigT",
  "LedcChannelConfigT",
  "",
  sizeof(LedcChannelConfigT),
  6,
  ledc_channel_config_t__field_descriptors,
  ledc_channel_config_t__field_indices_by_name,
  1,  ledc_channel_config_t__number_ranges,
  (ProtobufCMessageInit) ledc_channel_config_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ledc_intr_type_t__interrupt_type__enum_values_by_number[2] =
{
  { "LEDC_INTR_DISABLE", "LEDC_INTR_TYPE_T__INTERRUPT_TYPE__LEDC_INTR_DISABLE", 0 },
  { "LEDC_INTR_FADE_END", "LEDC_INTR_TYPE_T__INTERRUPT_TYPE__LEDC_INTR_FADE_END", 1 },
};
static const ProtobufCIntRange ledc_intr_type_t__interrupt_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex ledc_intr_type_t__interrupt_type__enum_values_by_name[2] =
{
  { "LEDC_INTR_DISABLE", 0 },
  { "LEDC_INTR_FADE_END", 1 },
};
const ProtobufCEnumDescriptor ledc_intr_type_t__interrupt_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ledc_intr_type_t.interrupt_type",
  "interrupt_type",
  "LedcIntrTypeT__InterruptType",
  "",
  2,
  ledc_intr_type_t__interrupt_type__enum_values_by_number,
  2,
  ledc_intr_type_t__interrupt_type__enum_values_by_name,
  1,
  ledc_intr_type_t__interrupt_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ledc_intr_type_t__field_descriptors[1] =
{
  {
    "intr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LedcIntrTypeT, intr),
    &ledc_intr_type_t__interrupt_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ledc_intr_type_t__field_indices_by_name[] = {
  0,   /* field[0] = intr */
};
static const ProtobufCIntRange ledc_intr_type_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ledc_intr_type_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ledc_intr_type_t",
  "LedcIntrTypeT",
  "LedcIntrTypeT",
  "",
  sizeof(LedcIntrTypeT),
  1,
  ledc_intr_type_t__field_descriptors,
  ledc_intr_type_t__field_indices_by_name,
  1,  ledc_intr_type_t__number_ranges,
  (ProtobufCMessageInit) ledc_intr_type_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ledc_channel_t__field_descriptors[1] =
{
  {
    "channel",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LedcChannelT, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ledc_channel_t__field_indices_by_name[] = {
  0,   /* field[0] = channel */
};
static const ProtobufCIntRange ledc_channel_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ledc_channel_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ledc_channel_t",
  "LedcChannelT",
  "LedcChannelT",
  "",
  sizeof(LedcChannelT),
  1,
  ledc_channel_t__field_descriptors,
  ledc_channel_t__field_indices_by_name,
  1,  ledc_channel_t__number_ranges,
  (ProtobufCMessageInit) ledc_channel_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ledc_mode_t__ledc_mode_e__enum_values_by_number[3] =
{
  { "LEDC_HIGH_SPEED_MODE", "LEDC_MODE_T__LEDC_MODE_E__LEDC_HIGH_SPEED_MODE", 0 },
  { "LEDC_LOW_SPEED_MODE", "LEDC_MODE_T__LEDC_MODE_E__LEDC_LOW_SPEED_MODE", 1 },
  { "LEDC_SPEED_MODE_MAX", "LEDC_MODE_T__LEDC_MODE_E__LEDC_SPEED_MODE_MAX", 2 },
};
static const ProtobufCIntRange ledc_mode_t__ledc_mode_e__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ledc_mode_t__ledc_mode_e__enum_values_by_name[3] =
{
  { "LEDC_HIGH_SPEED_MODE", 0 },
  { "LEDC_LOW_SPEED_MODE", 1 },
  { "LEDC_SPEED_MODE_MAX", 2 },
};
const ProtobufCEnumDescriptor ledc_mode_t__ledc_mode_e__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ledc_mode_t.ledc_mode_e",
  "ledc_mode_e",
  "LedcModeT__LedcModeE",
  "",
  3,
  ledc_mode_t__ledc_mode_e__enum_values_by_number,
  3,
  ledc_mode_t__ledc_mode_e__enum_values_by_name,
  1,
  ledc_mode_t__ledc_mode_e__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ledc_mode_t__field_descriptors[1] =
{
  {
    "ledc_speed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LedcModeT, ledc_speed),
    &ledc_mode_t__ledc_mode_e__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ledc_mode_t__field_indices_by_name[] = {
  0,   /* field[0] = ledc_speed */
};
static const ProtobufCIntRange ledc_mode_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ledc_mode_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ledc_mode_t",
  "LedcModeT",
  "LedcModeT",
  "",
  sizeof(LedcModeT),
  1,
  ledc_mode_t__field_descriptors,
  ledc_mode_t__field_indices_by_name,
  1,  ledc_mode_t__number_ranges,
  (ProtobufCMessageInit) ledc_mode_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i2c_operations_request__field_descriptors[2] =
{
  {
    "slave_sda_gpio",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(I2cOperationsRequest, slave_sda_gpio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slave_scl_gpio",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(I2cOperationsRequest, slave_scl_gpio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i2c_operations_request__field_indices_by_name[] = {
  1,   /* field[1] = slave_scl_gpio */
  0,   /* field[0] = slave_sda_gpio */
};
static const ProtobufCIntRange i2c_operations_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor i2c_operations_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "i2cOperationsRequest",
  "I2cOperationsRequest",
  "I2cOperationsRequest",
  "",
  sizeof(I2cOperationsRequest),
  2,
  i2c_operations_request__field_descriptors,
  i2c_operations_request__field_indices_by_name,
  1,  i2c_operations_request__number_ranges,
  (ProtobufCMessageInit) i2c_operations_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i2c_operations_response__field_descriptors[4] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(I2cOperationsResponse, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(I2cOperationsResponse, temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rel_hum",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(I2cOperationsResponse, rel_hum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pres",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(I2cOperationsResponse, pres),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i2c_operations_response__field_indices_by_name[] = {
  3,   /* field[3] = pres */
  2,   /* field[2] = rel_hum */
  0,   /* field[0] = success */
  1,   /* field[1] = temp */
};
static const ProtobufCIntRange i2c_operations_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor i2c_operations_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "i2cOperationsResponse",
  "I2cOperationsResponse",
  "I2cOperationsResponse",
  "",
  sizeof(I2cOperationsResponse),
  4,
  i2c_operations_response__field_descriptors,
  i2c_operations_response__field_indices_by_name,
  1,  i2c_operations_response__number_ranges,
  (ProtobufCMessageInit) i2c_operations_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor settimeofday_request__field_descriptors[1] =
{
  {
    "timeval",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SettimeofdayRequest, timeval),
    &time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned settimeofday_request__field_indices_by_name[] = {
  0,   /* field[0] = timeval */
};
static const ProtobufCIntRange settimeofday_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor settimeofday_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SettimeofdayRequest",
  "SettimeofdayRequest",
  "SettimeofdayRequest",
  "",
  sizeof(SettimeofdayRequest),
  1,
  settimeofday_request__field_descriptors,
  settimeofday_request__field_indices_by_name,
  1,  settimeofday_request__number_ranges,
  (ProtobufCMessageInit) settimeofday_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor settimeofday_response__field_descriptors[2] =
{
  {
    "return_value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(SettimeofdayResponse, return_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_alt",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(SettimeofdayResponse, errno_alt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned settimeofday_response__field_indices_by_name[] = {
  1,   /* field[1] = errno_alt */
  0,   /* field[0] = return_value */
};
static const ProtobufCIntRange settimeofday_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor settimeofday_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SettimeofdayResponse",
  "SettimeofdayResponse",
  "SettimeofdayResponse",
  "",
  sizeof(SettimeofdayResponse),
  2,
  settimeofday_response__field_descriptors,
  settimeofday_response__field_indices_by_name,
  1,  settimeofday_response__number_ranges,
  (ProtobufCMessageInit) settimeofday_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gettimeofday_request__field_descriptors[1] =
{
  {
    "stub",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(GettimeofdayRequest, stub),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gettimeofday_request__field_indices_by_name[] = {
  0,   /* field[0] = stub */
};
static const ProtobufCIntRange gettimeofday_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gettimeofday_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GettimeofdayRequest",
  "GettimeofdayRequest",
  "GettimeofdayRequest",
  "",
  sizeof(GettimeofdayRequest),
  1,
  gettimeofday_request__field_descriptors,
  gettimeofday_request__field_indices_by_name,
  1,  gettimeofday_request__number_ranges,
  (ProtobufCMessageInit) gettimeofday_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gettimeofday_response__field_descriptors[3] =
{
  {
    "return_value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(GettimeofdayResponse, return_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_alt",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(GettimeofdayResponse, errno_alt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeval",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GettimeofdayResponse, timeval),
    &time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gettimeofday_response__field_indices_by_name[] = {
  1,   /* field[1] = errno_alt */
  0,   /* field[0] = return_value */
  2,   /* field[2] = timeval */
};
static const ProtobufCIntRange gettimeofday_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gettimeofday_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GettimeofdayResponse",
  "GettimeofdayResponse",
  "GettimeofdayResponse",
  "",
  sizeof(GettimeofdayResponse),
  3,
  gettimeofday_response__field_descriptors,
  gettimeofday_response__field_indices_by_name,
  1,  gettimeofday_response__number_ranges,
  (ProtobufCMessageInit) gettimeofday_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ledc_channel_config__request__field_descriptors[1] =
{
  {
    "ledc_conf",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LedcChannelConfigRequest, ledc_conf),
    &ledc_channel_config_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ledc_channel_config__request__field_indices_by_name[] = {
  0,   /* field[0] = ledc_conf */
};
static const ProtobufCIntRange ledc_channel_config__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ledc_channel_config__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ledc_channel_config_Request",
  "LedcChannelConfigRequest",
  "LedcChannelConfigRequest",
  "",
  sizeof(LedcChannelConfigRequest),
  1,
  ledc_channel_config__request__field_descriptors,
  ledc_channel_config__request__field_indices_by_name,
  1,  ledc_channel_config__request__number_ranges,
  (ProtobufCMessageInit) ledc_channel_config__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ledc_channel_config__response__field_descriptors[1] =
{
  {
    "config_status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LedcChannelConfigResponse, config_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ledc_channel_config__response__field_indices_by_name[] = {
  0,   /* field[0] = config_status */
};
static const ProtobufCIntRange ledc_channel_config__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ledc_channel_config__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ledc_channel_config_Response",
  "LedcChannelConfigResponse",
  "LedcChannelConfigResponse",
  "",
  sizeof(LedcChannelConfigResponse),
  1,
  ledc_channel_config__response__field_descriptors,
  ledc_channel_config__response__field_indices_by_name,
  1,  ledc_channel_config__response__number_ranges,
  (ProtobufCMessageInit) ledc_channel_config__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__field_descriptors[4] =
{
  {
    "settimeofday_request",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, request_func_case),
    offsetof(Request, settimeofday_request),
    &settimeofday_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gettimeofday_request",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, request_func_case),
    offsetof(Request, gettimeofday_request),
    &gettimeofday_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ledc_channel_config_request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, request_func_case),
    offsetof(Request, ledc_channel_config_request),
    &ledc_channel_config__request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i2c_request",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, request_func_case),
    offsetof(Request, i2c_request),
    &i2c_operations_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  1,   /* field[1] = gettimeofday_request */
  3,   /* field[3] = i2c_request */
  2,   /* field[2] = ledc_channel_config_request */
  0,   /* field[0] = settimeofday_request */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  4,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[4] =
{
  {
    "settimeofday_response",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, response_func_case),
    offsetof(Response, settimeofday_response),
    &settimeofday_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gettimeofday_response",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, response_func_case),
    offsetof(Response, gettimeofday_response),
    &gettimeofday_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ledc_channel_config_response",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, response_func_case),
    offsetof(Response, ledc_channel_config_response),
    &ledc_channel_config__response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i2c_response",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, response_func_case),
    offsetof(Response, i2c_response),
    &i2c_operations_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  1,   /* field[1] = gettimeofday_response */
  3,   /* field[3] = i2c_response */
  2,   /* field[2] = ledc_channel_config_response */
  0,   /* field[0] = settimeofday_response */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  4,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor x_rpcmessage__field_descriptors[3] =
{
  {
    "request",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XRPCMessage, message_type_case),
    offsetof(XRPCMessage, request),
    &request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XRPCMessage, message_type_case),
    offsetof(XRPCMessage, response),
    &response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_stamp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(XRPCMessage, time_stamp),
    &time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned x_rpcmessage__field_indices_by_name[] = {
  0,   /* field[0] = request */
  1,   /* field[1] = response */
  2,   /* field[2] = time_stamp */
};
static const ProtobufCIntRange x_rpcmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor x_rpcmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xRPCMessage",
  "XRPCMessage",
  "XRPCMessage",
  "",
  sizeof(XRPCMessage),
  3,
  x_rpcmessage__field_descriptors,
  x_rpcmessage__field_indices_by_name,
  1,  x_rpcmessage__number_ranges,
  (ProtobufCMessageInit) x_rpcmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
